## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">PART- 04- GET DUMMIES</p>

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../data/processed/outlier_cleaned_data.csv")
#df

In [3]:
df.shape

(15915, 31)

In [4]:
df.columns

Index(['make_model', 'body_type', 'price', 'vat', 'km', 'hp', 'type',
       'inspection_new', 'warranty', 'body_color', 'paint_type', 'nr_of_doors',
       'nr_of_seats', 'gearing_type', 'displacement', 'cylinders', 'weight',
       'drive_chain', 'fuel', 'co2_emission', 'emission_class',
       'comfort_and_convenience', 'entertainment_and_media', 'extras',
       'safety_and_security', 'gears', 'registration_year', 'age',
       'upholstery_type', 'cons_comb', 'prev_owner'],
      dtype='object')

In [5]:
# Applied get_dummies method to object columns to convert all values to numerical

In [6]:
object_columns = ['make_model', 'body_type', 'vat', 'type', 'body_color', 'paint_type', 
                  'gearing_type', 'drive_chain', 'fuel', 'emission_class']
df_dummied = pd.get_dummies(df, columns= object_columns, drop_first=True, dtype=int)

In [7]:
df_dummied.columns

Index(['price', 'km', 'hp', 'inspection_new', 'warranty', 'nr_of_doors',
       'nr_of_seats', 'displacement', 'cylinders', 'weight', 'co2_emission',
       'comfort_and_convenience', 'entertainment_and_media', 'extras',
       'safety_and_security', 'gears', 'registration_year', 'age',
       'upholstery_type', 'cons_comb', 'prev_owner', 'make_model_Audi A2',
       'make_model_Audi A3', 'make_model_Opel Astra', 'make_model_Opel Corsa',
       'make_model_Opel Insignia', 'make_model_Renault Clio',
       'make_model_Renault Duster', 'make_model_Renault Espace',
       'body_type_Convertible', 'body_type_Coupe', 'body_type_Off-Road',
       'body_type_Other', 'body_type_Sedans', 'body_type_Station wagon',
       'body_type_Transporter', 'body_type_Van', 'vat_VAT deductible',
       'vat_VAT undeductible', 'type_Employee's car', 'type_New',
       'type_Pre-registered', 'type_Used', 'body_color_Black',
       'body_color_Blue', 'body_color_Bronze', 'body_color_Brown',
       'body_color_Green', 'body_color_Grey', 'body_color_Orange',
       'body_color_Red', 'body_color_Silver', 'body_color_Violet',
       'body_color_White', 'body_color_Yellow', 'paint_type_Perl effect',
       'paint_type_Uni/basic', 'gearing_type_Manual',
       'gearing_type_Semi-automatic', 'drive_chain_front', 'drive_chain_rear',
       'fuel_Diesel', 'fuel_Electric', 'fuel_LPG/CNG', 'emission_class_Euro 4',
       'emission_class_Euro 5', 'emission_class_Euro 6'],
      dtype='object')

In [8]:
df_dummied["make_model_Audi A3"]

0        0
1        0
2        0
3        0
4        0
        ..
15910    0
15911    0
15912    0
15913    0
15914    0
Name: make_model_Audi A3, Length: 15915, dtype: int64

In [9]:
df['extras'] = (
    df['extras']
    .astype(str)
    .str.replace('[', '', regex=False)
    .str.replace(']', '', regex=False)
)

extras_dummies = df['extras'].str.get_dummies(sep=',')

In [10]:
extras_dummies

,Alloy wheels,Cab or rented Car,Catalytic Converter,Handicapped enabled,Right hand drive,Roof rack,Shift paddles,Ski bag,Sliding door,Sport package,Sport seats,Sport suspension,Touch screen,Trailer hitch,Tuned car,Voice Control,Winter tyres,nan
0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
1,1,0,0,0,0,0,0,0,0,0,1,1,0,0,0,1,0,0
2,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
3,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0
4,1,0,0,0,0,0,0,0,0,1,0,1,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15910,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
15911,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0
15912,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
15913,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
15914,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0

In [11]:
df['extras'] = (
    df['extras']
    .astype(str)
    .str.replace('[', '', regex=False)
    .str.replace(']', '', regex=False)
)

df_E = df['extras'].str.get_dummies(sep=',')

In [12]:
df_E[df_E.nan == 1]

,Alloy wheels,Cab or rented Car,Catalytic Converter,Handicapped enabled,Right hand drive,Roof rack,Shift paddles,Ski bag,Sliding door,Sport package,Sport seats,Sport suspension,Touch screen,Trailer hitch,Tuned car,Voice Control,Winter tyres,nan
9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
30,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
36,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
44,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
51,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15800,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
15801,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
15846,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
15850,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
15860,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1

In [13]:
df_E.drop(columns = ['nan'], inplace=True)

In [14]:
# Applied get_dummies method to columns extras, comfort_convenience, entertainment_media

In [15]:
df['comfort_and_convenience'] = (
    df['comfort_and_convenience']
    .astype(str)
    .str.replace('[', '', regex=False)
    .str.replace(']', '', regex=False)
)

df_C = df['comfort_and_convenience'].str.get_dummies(sep=',')

In [16]:
df_C.drop(columns=['nan'], inplace=True)

In [17]:
df['entertainment_and_media'][1]

"'Bluetooth', 'Hands-free equipment', 'On-board computer', 'Radio', 'Sound system'"

In [18]:
df['entertainment_and_media'] = (
    df['entertainment_and_media']
    .astype(str)
    .str.replace('[', '', regex=False)
    .str.replace(']', '', regex=False)
)

df_Ent = df['entertainment_and_media'].str.get_dummies(sep=',')

In [19]:
df_Ent.drop(columns=['nan'], inplace=True)

In [20]:
df_Ent

,'CD player','Digital radio','Hands-free equipment','MP3','On-board computer','Radio','Sound system','Television','USB','Bluetooth','CD player','Digital radio','Hands-free equipment','MP3','On-board computer','Radio','Sound system','USB'
0,0,0,1,0,1,1,0,0,0,1,0,0,0,0,0,0,0,0
1,0,0,1,0,1,1,1,0,0,1,0,0,0,0,0,0,0,0
2,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0
3,1,0,1,1,1,1,1,0,1,1,0,0,0,0,0,0,0,0
4,1,0,1,1,1,1,0,0,1,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15910,0,1,1,0,1,1,0,0,1,1,0,0,0,0,0,0,0,0
15911,0,1,1,0,0,1,0,0,1,1,0,0,0,0,0,0,0,0
15912,0,0,1,0,1,1,0,0,0,1,0,0,0,0,0,0,0,0
15913,0,1,0,0,0,1,0,0,1,1,0,0,0,0,0,0,0,0
15914,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1

In [21]:
df['safety_and_security'] = (
    df['safety_and_security']
    .astype(str)
    .str.replace('[', '', regex=False)
    .str.replace(']', '', regex=False)
)

df_sec = df['safety_and_security'].str.get_dummies(sep=',')

In [22]:
df_sec.drop(columns=['nan'], inplace=True)

In [23]:
df_E.sum()

Alloy wheels           11291
Cab or rented Car        310
Catalytic Converter     2258
Handicapped enabled       52
Right hand drive           3
Roof rack               2646
Shift paddles            508
Ski bag                  247
Sliding door               3
Sport package           1197
Sport seats             3098
Sport suspension        1618
Touch screen            4043
Trailer hitch            654
Tuned car                 13
Voice Control           4326
Winter tyres             246
dtype: int64

In [24]:
#df_E.columns = df_E.columns.str.replace("'","").str.lower().str.replace(" ","_")

In [25]:
df_E.columns= df_E.columns.str.replace(" ","_").str.lower().str.replace(",","")

In [26]:
df_E.sum().sort_values(ascending=False)

alloy_wheels           11291
voice_control           4326
touch_screen            4043
sport_seats             3098
roof_rack               2646
catalytic_converter     2258
sport_suspension        1618
sport_package           1197
trailer_hitch            654
shift_paddles            508
cab_or_rented_car        310
ski_bag                  247
winter_tyres             246
handicapped_enabled       52
tuned_car                 13
right_hand_drive           3
sliding_door               3
dtype: int64

In [27]:
df_C.sum().sort_values(ascending=False)

'Air conditioning'                        14311
 'Power windows'                          13887
 'Electrical side mirrors'                11790
 'Multi-function steering wheel'          11055
 'Cruise control'                         10534
 'Park Distance Control'                  10180
 'Parking assist system sensors rear'      9693
 'Leather steering wheel'                  9368
 'Start-stop system'                       8879
 'Automatic climate control'               8745
 'Rain sensor'                             8611
 'Navigation system'                       8118
 'Light sensor'                            7666
 'Armrest'                                 7126
 'Seat heating'                            7077
 'Hill Holder'                             6734
 'Parking assist system sensors front'     5838
 'Parking assist system camera'            3421
 'Lumbar support'                          3226
 'Heated steering wheel'                   3015
 'Keyless central door lock'               2613
 'Split rear seats'                        2387
 'Electrically adjustable seats'           1863
 'Tinted windows'                          1444
 'Electric tailgate'                       1003
 'Electrically heated windshield'           932
 'Seat ventilation'                         834
 'Parking assist system self-steering'      768
 'Heads-up display'                         605
 'Panorama roof'                            550
 'Sunroof'                                  364
 'Massage seats'                            360
'Cruise control'                            343
 'Auxiliary heating'                        264
'Armrest'                                    98
'Electrical side mirrors'                    89
 'Air suspension'                            59
 'Leather seats'                             48
'Navigation system'                          46
 'Wind deflector'                            41
'Multi-function steering wheel'              24
'Power windows'                              23
'Leather steering wheel'                     15
 'Windshield'                                12
'Park Distance Control'                       8
'Hill Holder'                                 8
'Sunroof'                                     8
'Electrically heated windshield'              5
'Light sensor'                                4
'Air suspension'                              3
'Electrically adjustable seats'               3
'Heated steering wheel'                       2
'Auxiliary heating'                           2
'Heads-up display'                            1
'Panorama roof'                               1
 'Electric Starter'                           1
'Rain sensor'                                 1
dtype: int64

In [28]:
df_E.drop(["right_hand_drive","sliding_door","tuned_car","handicapped_enabled"], axis=1,inplace=True)

In [29]:
#df_C.columns = df_C.columns.str.replace(" ","_").str.lower().str.replace(",","")

In [30]:

df_C.columns = (
    df_C.columns
    .astype(str)
    .str.strip()
    .str.lower()
    .str.replace("[", "", regex=False)
    .str.replace("]", "", regex=False)
    .str.replace("'", "", regex=False)
    .str.replace(" ", "_", regex=False)
    
)

In [31]:
df_C.sum().sort_values(ascending=False)

air_conditioning                       14311
power_windows                          13887
electrical_side_mirrors                11790
multi-function_steering_wheel          11055
cruise_control                         10534
park_distance_control                  10180
parking_assist_system_sensors_rear      9693
leather_steering_wheel                  9368
start-stop_system                       8879
automatic_climate_control               8745
rain_sensor                             8611
navigation_system                       8118
light_sensor                            7666
armrest                                 7126
seat_heating                            7077
hill_holder                             6734
parking_assist_system_sensors_front     5838
parking_assist_system_camera            3421
lumbar_support                          3226
heated_steering_wheel                   3015
keyless_central_door_lock               2613
split_rear_seats                        2387
electrically_adjustable_seats           1863
tinted_windows                          1444
electric_tailgate                       1003
electrically_heated_windshield           932
seat_ventilation                         834
parking_assist_system_self-steering      768
heads-up_display                         605
panorama_roof                            550
sunroof                                  364
massage_seats                            360
cruise_control                           343
auxiliary_heating                        264
armrest                                   98
electrical_side_mirrors                   89
air_suspension                            59
leather_seats                             48
navigation_system                         46
wind_deflector                            41
multi-function_steering_wheel             24
power_windows                             23
leather_steering_wheel                    15
windshield                                12
park_distance_control                      8
hill_holder                                8
sunroof                                    8
electrically_heated_windshield             5
light_sensor                               4
air_suspension                             3
electrically_adjustable_seats              3
heated_steering_wheel                      2
auxiliary_heating                          2
heads-up_display                           1
panorama_roof                              1
electric_starter                           1
rain_sensor                                1
dtype: int64

In [32]:
df.columns

Index(['make_model', 'body_type', 'price', 'vat', 'km', 'hp', 'type',
       'inspection_new', 'warranty', 'body_color', 'paint_type', 'nr_of_doors',
       'nr_of_seats', 'gearing_type', 'displacement', 'cylinders', 'weight',
       'drive_chain', 'fuel', 'co2_emission', 'emission_class',
       'comfort_and_convenience', 'entertainment_and_media', 'extras',
       'safety_and_security', 'gears', 'registration_year', 'age',
       'upholstery_type', 'cons_comb', 'prev_owner'],
      dtype='object')

In [33]:
index_leather = df_dummied[(df_dummied['upholstery_type']=='Part leather') \
           | (df_dummied['upholstery_type']=='Full leather') \
           | (df_dummied['upholstery_type']=='alcantara') \
           | (df_dummied['upholstery_type']=='Velour')]['upholstery_type'].index

In [34]:
df_C.loc[index_leather, 'leather_seats'] = 1

In [35]:
df_C.drop(columns=["electric_starter","windshield","wind_deflector", "air_suspension"], inplace=True)

In [36]:
#df['extras'].astype('str').str.replace('[','').str.replace("]",'').str.get_dummies(sep=', ')